# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
trigger:
  branches:
    include:
      - master
      - testing-CI/CD
        

strategy:
  matrix:
    ubuntu:
      imagename: 'ubuntu-latest'
    mac:
      imagename: 'macos-latest'


pool:
  vmImage: $(imagename)

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
